version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - standalone-chrome
  selenium-hub:
    image: selenium/hub:3.141.59-neon
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  standalone-chrome:
    ports:
      - "4444:4444"
    volumes:
      - "/dev/shm:/dev/shm"
    image: "selenium/standalone-chrome:3.141.59-neon"
