version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - chrome
  selenium-hub:
    image: selenium/hub:3
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh"]
      interval: 15s
      timeout: 30s
      retries: 5
  chrome:
    image: selenium/node-chrome:3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  standalone-chrome:
    ports:
      - "4444:4444"
    volumes:
      - "/dev/shm:/dev/shm"
    image: "selenium/standalone-chrome:3"
